version: "3"
services:
  postgres:
    image: postgres
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready","-U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
